apiVersion: apps/v1
kind: Deployment
metadata:
  name: maf-backend-deployment
  labels:
    app: maf-backend
spec:
  replicas: 1
  selector:  
    matchLabels: 
      app: maf-backend 
  template:
    metadata:
      name: maf-backend-pod
      labels:
        app: maf-backend
    spec:
      containers:
      - name: maf-backend
        image: ddplatform-pvt-registry:443/maf-backend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      restartPolicy: Always